# Generated by Django 3.1.4 on 2021-09-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_auto_20210905_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author1',
            new_name='Author',
        ),
    ]
